/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as ExpensesNewRouteImport } from './routes/expenses.new'
import { Route as DepositsNewRouteImport } from './routes/deposits.new'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesNewRoute = ExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsNewRoute = DepositsNewRouteImport.update({
  id: '/deposits/new',
  path: '/deposits/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/deposits/new': typeof DepositsNewRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/deposits/new': typeof DepositsNewRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses': typeof ExpensesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/members': typeof MembersRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/deposits/new': typeof DepositsNewRoute
  '/expenses/new': typeof ExpensesNewRoute
  '/expenses/': typeof ExpensesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/deposits/new'
    | '/expenses/new'
    | '/expenses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/deposits/new'
    | '/expenses/new'
    | '/expenses'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/members'
    | '/onboarding'
    | '/profile'
    | '/reports'
    | '/deposits/new'
    | '/expenses/new'
    | '/expenses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MembersRoute: typeof MembersRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  DepositsNewRoute: typeof DepositsNewRoute
  ExpensesNewRoute: typeof ExpensesNewRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/new': {
      id: '/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ExpensesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits/new': {
      id: '/deposits/new'
      path: '/deposits/new'
      fullPath: '/deposits/new'
      preLoaderRoute: typeof DepositsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MembersRoute: MembersRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  DepositsNewRoute: DepositsNewRoute,
  ExpensesNewRoute: ExpensesNewRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
